### ISSUE TITLE
[epic] Entities plugin for Kazana

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana#11]

**Comment by gr2m** [comment]
### What we want

- Bootstrap data into database
  - do not overwrite existing data
  - do not create data that has been deleted
- REST API, to read and write
- client API for simpler look up
- search

### Use cases

1. Matching of raw data with entities, e.g. if raw data provides names of regions / districts,
   we want to match them with region / district entities

### Notes

- We can re-use a lot of https://github.com/eHealthAfrica/mnutrition-entities

### Todo

- [ ] create a kazana plugin with sample data to be bootstrapped
- [ ] figure out a way to only bootstrap data that does not exist / that was not deleted before
- [ ] write tests for all this
- [ ] Add REST APIs to manage entities (require roles, admins by default)
- [ ] Add REST APIs to read entities (configurable, require roles, or public)
- [ ] Implement search
- [ ] Implement client API, usable in both, client & server.

**Comment by patriciagarcia** [comment]
Implemented here https://github.com/eHealthAfrica/kazana-entities. Follow up issues have been created in that repo for missing features.
