### ISSUE TITLE
[epic] User management capabilities

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana#125]

**Comment by gr2m** [comment]
Here’s the plan:

- [ ] fork [hoodie-server-account](https://github.com/hoodiehq/hoodie-server-account) & [hoodie-client-account](https://github.com/hoodiehq/hoodie-client-account) to [eHealthAfrica](https://github.com/eHealthAfrica)
- [ ] add hoodie-server-account & hoodie-client-account forks as dependencies to [kazana-account](https://github.com/eHealthAfrica/kazana-account)
- [ ] deprecate the current routes, but make sure they still work, so we don’t break existing kazana apps
- [ ] implement the missing features needed for user management in hoodie-server-account, send PR
- [ ] implement the missing features needed for user management in hoodie-client-account, send PR
- [ ] add kazana-account-app as dependency to kazana-account, serve at root, so it gets served at `/kazana/account` in the apps
- [ ] wire up kazana-account-app to use the hoodie-client-account admin API
- [ ] Once our PRs get merged & released, remove our forks & update the kazana-account dependencies

**Comment by ehealth-waffle** [comment]
note to self (@gr2m): use `/v1` route prefix to avoid route conflicts with existing ones, so we can support both & add deprecations to old ones
