### ISSUE TITLE
[epic] test coverage

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana#131]
### User story
_As a Kazana developer, I want to have proper (unit) test coverage, so that I can be confident of making changes and adding features without introducing regressions_

### Tasks
- [x] Add coverage measurement and coverage badge (in README.md) (ready: [kazana-entities#19](https://github.com/eHealthAfrica/kazana-entities/pull/19))
- [x] Add coverage measurement and coverage badge (in README.md) (ready: https://github.com/eHealthAfrica/kazana-transform/pull/16)
- [x] Add coverage measurement and coverage badge (in README.md) (ready: https://github.com/eHealthAfrica/kazana-email-box/pull/17)
- [x] Add coverage badge (in README.md) for [kazana-bootstrap#22](https://github.com/eHealthAfrica/kazana-bootstrap/issues/22)
- [x]  [![Coverage Status](https://coveralls.io/repos/eHealthAfrica/kazana-server/badge.svg?branch=master)](https://coveralls.io/r/eHealthAfrica/kazana-server?branch=master) kazana-server
- [x]  [![Coverage Status](https://coveralls.io/repos/eHealthAfrica/kazana-entities/badge.svg?branch=master)](https://coveralls.io/r/eHealthAfrica/kazana-entities?branch=master) kazana-entities
- [x] [![Coverage Status](https://coveralls.io/repos/eHealthAfrica/kazana-transform/badge.svg?branch=master)](https://coveralls.io/r/eHealthAfrica/kazana-transform?branch=master) kazana-transform
- [x] [![Coverage Status](https://coveralls.io/repos/eHealthAfrica/kazana-account/badge.svg?branch=master)](https://coveralls.io/r/eHealthAfrica/kazana-account?branch=master) kazana-account
- [x] [![Coverage Status](https://coveralls.io/repos/eHealthAfrica/kazana-raw-data/badge.svg?branch=master)](https://coveralls.io/r/eHealthAfrica/kazana-raw-data?branch=master) kazana-raw-data
- [x] [![Coverage Status](https://coveralls.io/repos/eHealthAfrica/kazana-config/badge.svg?branch=master)](https://coveralls.io/r/eHealthAfrica/kazana-config?branch=master) kazana-config
- [x] [![Coverage Status](https://coveralls.io/repos/eHealthAfrica/kazana-bootstrap/badge.svg?branch=master)](https://coveralls.io/r/eHealthAfrica/kazana-bootstrap?branch=master) kazana-bootstrap
- [x] setup protection for all `master` branchs, require green coveralls status

### Acceptance criteria
- [x] 100% coverage reached in all repos

**Comment by patriciagarcia** [comment]
what's an acceptable coverage percentage? @gr2m, @jo, @quesebifurcan, @readevalprint

**Comment by gr2m** [comment]
Yes, 100%.

**Comment by patriciagarcia** [comment]
anything missing here? cc/ @jo, @gr2m, @readevalprint

**Comment by jo** [comment]
I want those coverage badges in the README of this repo

**Comment by gr2m** [comment]
Once they are all 100% we can prevent pushes to `master` branches of all these repos if coverage falls below, so then we won’t need it anymore. We can add that as requirement to this issue?

**Comment by jo** [comment]
Agreed.

**Comment by gr2m** [comment]
\o/

**Comment by FrancescoK** [comment]
:clap: :clap: :clap:
